SET SCHEMA BOOKMARK_MANAGER_SCHEMA;

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, CREATE_DATE, PARENT_ID, VERSION)
VALUES(NEXTVAL('CATEGORIES_SEQ'), 'CATEGORY1', 'CATEGORY1', CURRENT_TIMESTAMP(), NULL, 0);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, CREATE_DATE, PARENT_ID, VERSION)
VALUES (NEXTVAL('CATEGORIES_SEQ'), 'CATEGORY2', 'CATEGORY2', CURRENT_TIMESTAMP(), 1, 0);