SET SCHEMA BOOKMARK_MANAGER_SCHEMA;

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, ICON, CREATE_DATE, PARENT_ID)
VALUES(NEXTVAL('CATEGORIES_SEQ'), 'CATEGORY1', 'CATEGORY1', NULL, CURRENT_TIMESTAMP(), NULL );
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, ICON, CREATE_DATE, PARENT_ID)
VALUES (NEXTVAL('CATEGORIES_SEQ'), 'CATEGORY2', 'CATEGORY2', NULL, CURRENT_TIMESTAMP(), 37);