SET SCHEMA BOOKMARK_MANAGER_SCHEMA;

ALTER TABLE IF EXISTS CATEGORIES DROP CONSTRAINT IF EXISTS FK_PARENT_CATEGORY;
ALTER TABLE IF EXISTS CATEGORIES DROP CONSTRAINT IF EXISTS FK_TOP_CATEGORY;
ALTER TABLE IF EXISTS BOOKMARKS DROP CONSTRAINT IF EXISTS FK_BOOKMARKS_CATEGORIES;
ALTER TABLE IF EXISTS AUTHORITIES DROP CONSTRAINT IF EXISTS FK_AUTHORITIES_USERS;