SET SCHEMA BOOKMARK_MANAGER_SCHEMA;

-- CONSTRAINTS FOR TABLE 'CATEGORIES'
ALTER TABLE CATEGORIES
  ADD FOREIGN KEY (PARENT_ID)
REFERENCES CATEGORIES (ID);

-- CONSTRAINTS FOR TABLE 'BOOKMARKS'
ALTER TABLE BOOKMARKS
  ADD FOREIGN KEY (CATEGORY_ID)
REFERENCES CATEGORIES (ID);